"""Добавлено каскадное удаление продуктов после удаления категории

Revision ID: b33b3042e84a
Revises: 538f964bf3e8
Create Date: 2024-09-05 20:43:49.120902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33b3042e84a'
down_revision: Union[str, None] = '538f964bf3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['product_category'], ['category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['product_category'], ['category_id'])
    # ### end Alembic commands ###
